### ISSUE TITLE
Error while using library in background service

### ISSUE THREAD

**Issue by shantanu1227** [quentin7b/android-location-tracker#15]
```
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
    at android.os.Handler.<init>(Handler.java:200)
    at android.os.Handler.<init>(Handler.java:114)
    at android.location.LocationManager$ListenerTransport$1.<init>(LocationManager.java:223)
    at android.location.LocationManager$ListenerTransport.<init>(LocationManager.java:223)
    at android.location.LocationManager.wrapListener(LocationManager.java:851)
    at android.location.LocationManager.requestLocationUpdates(LocationManager.java:864)
    at android.location.LocationManager.requestLocationUpdates(LocationManager.java:459)
    at fr.quentinklein.slt.LocationTracker.startListening(LocationTracker.java:111)
    at com.mypackage.api.gcm.GcmMessageListener.sendLocation(GcmMessageListener.java:85)
```

**Comment by qk7b** [comment]
Thanks for the issue ! 

Just, what are you doing in `sendLocation` ?

**Comment by shantanu1227** [comment]
```
 My send location is just initalizing the tracker

public void sendLocation() {
    final Context context = this;
    if (ActivityCompat.checkSelfPermission(context, Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED && ActivityCompat.checkSelfPermission(context, Manifest.permission.ACCESS_COARSE_LOCATION) != PackageManager.PERMISSION_GRANTED) {
        return;
    }
    final LocationTracker tracker = new LocationTracker(context) {
        @Override
        public void onLocationFound(@NonNull final Location location) {
            stopListening();
            System.out.println(location.getLatitude() +""+location.getLongitude());
        }

        @Override
        public void onTimeout() {
            stopListening();
            Log.v("GCM", "Location NULL");
        }
    };
    tracker.startListening();
}
```

`

**Comment by shantanu1227** [comment]
Solved it using below code:

```
private class ThreadClass extends Thread {

    Context context;
    public ThreadClass(Context context) {
        this.context = context;
    }

    @Override
    public void run() {
        Looper.prepare();

        if (ActivityCompat.checkSelfPermission(context, Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED && ActivityCompat.checkSelfPermission(context, Manifest.permission.ACCESS_COARSE_LOCATION) != PackageManager.PERMISSION_GRANTED) {
            return;
        }
        LocationTracker tracker = new LocationTracker(context, new TrackerSettings()
                .setUsePassive(false))
        {
            @Override
            public void onLocationFound(@NonNull Location location) {
                stopListening();
                System.out.println(location.getLatitude() + "" + location.getLongitude());
                threadLooper.quit();
            }

            @Override
            public void onTimeout() {
                stopListening();
                Log.v("GCM", "Location NULL");
                threadLooper.quit();
            }
        };
        threadLooper = Looper.myLooper();
        tracker.startListening();
        Looper.loop();  // loop until "quit()" is called.
    }
}
```

**Comment by qk7b** [comment]
Ok ! Nice to see it is working. I close the issue

**Comment by AhmedHamedTN** [comment]
@shantanu1227 can you please share threadlooper class ? i would like to have an idea on how u implemented a solution with this library

**Comment by iC00kScripts** [comment]
just after the class declaration
Looper threadlooper;
