### ISSUE TITLE
Getting 'Provider is not enabled | ProviderError{provider='network'}'  on calling 'tracker.startListening();'.

### ISSUE THREAD

**Issue by HammadNasir** [quentin7b/android-location-tracker#19]
I'm using your library in my app and while trying this code:
```

settings =
                new TrackerSettings()
                        .setUseGPS(true)
                        .setUseNetwork(true)
                        .setUsePassive(true)
                        .setTimeBetweenUpdates(30 * 60 * 1000);

        tracker = new LocationTracker(getBaseContext(), settings) {
            @Override
            public void onLocationFound(Location location) {
                // Do some stuff
                currentLatDouble = location.getLatitude();
                currentLngDouble = location.getLongitude();
            }

            @Override
            public void onTimeout() {

            }
        };
        tracker.startListening();
```

I'm getting these errors:

```
W/LocationTracker: Provider (gps)
                   fr.quentinklein.slt.ProviderError: Provider is not enabled | ProviderError{provider='gps'}

W/LocationTracker: Provider (network)
                   fr.quentinklein.slt.ProviderError: Provider is not enabled | ProviderError{provider='network'}
```

even when the 'WiFi' is enabled!

Please help with this issue!

**Comment by qk7b** [comment]
Looks like the providers are turned off.

You can try to call this when this kind of warning is sent to check everything is fine with the providers
```java
context.startActivity(new Intent(Settings.ACTION_LOCATION_SOURCE_SETTINGS));
```

**Comment by HammadNasir** [comment]
@quentin7b hey, is WiFi a network provider? Because it is on and I don't want the GPS to be turned on for getting location.

**Comment by qk7b** [comment]
I guess.
There are 3 providers
* Network 
* GPS
* Passive 
So when you ask for locations with:

```java
.setUseGPS(true)
.setUseNetwork(true)
```

Without the GPS, you'll get the warning 
```
W/LocationTracker: Provider (gps)
                   fr.quentinklein.slt.ProviderError: Provider is not enabled | ProviderError{provider='gps'}
```

But the network should work with wifi as exlplained here : https://developer.android.com/reference/android/location/LocationManager.html#NETWORK_PROVIDER

**Comment by HammadNasir** [comment]
@quentin7b yeah, this is what I mean... when my WiFi is enabled then why am I getting this error:

 ```
W/LocationTracker: Provider (network)
                   fr.quentinklein.slt.ProviderError: Provider is not enabled | ProviderError{provider='network'}
```

Do I need to write a code which enables it manually or is there something to do with the ```LocationManager```?

**Comment by HammadNasir** [comment]
@quentin7b please respond, buddy.

**Comment by qk7b** [comment]
To be honest, I don't know what to do.
If you are sure that the network provider, wifi in your case, is activated, then the error should not be raised and the locations must be updated. 

In addition to having this error, do you have the updates ?

**Comment by HammadNasir** [comment]
@quentin7b what updates are you talking bout?

**Comment by qk7b** [comment]
The locations updates

**Comment by enzonotario** [comment]
Hi @quentin7b ! First, I don't speak english, but...
I'm trying to use this library. I came from smart-location-lib because I can't get the location from network with that library. With your library I get this error:
```
04-14 01:37:53.723 3677-3677/com.hawk.angela W/LocationTracker: Provider (network)
fr.quentinklein.slt.ProviderError: Provider is not enabled | ProviderError{provider='network'}
    at fr.quentinklein.slt.LocationTracker.startListening(LocationTracker.java:121)
    at com.hawk.angela.place.activities.PlacePickerActivity.goToMyPosition(PlacePickerActivity.java:489)
    at com.hawk.angela.place.activities.PlacePickerActivity_ViewBinding$3.doClick(PlacePickerActivity_ViewBinding.java:63)
    at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
    at android.view.View.performClick(View.java:5198)
    at android.view.View$PerformClick.run(View.java:21147)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

I'm totally sure that the WIFI is ON. I'm trying it with a Samsung Grand Prime (Android 4.4.4), and also in an AVD Nexus 6 API 23, that shows me the same error that my real device shows me...

I also don't receive any location updates (as you ask above)... and after a time it shows me:
```
04-14 01:38:53.727 3677-3677/com.hawk.angela I/LocationTracker: No location found in the meantime
04-14 01:38:53.727 3677-3677/com.hawk.angela I/LocationTracker: LocationTracked has stopped listening for location updates
```

The code that I'm trying is the one that the readme shows:
```
if (    ContextCompat.checkSelfPermission(getApplicationContext(), Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED
        && ContextCompat.checkSelfPermission(getApplicationContext(), Manifest.permission.ACCESS_COARSE_LOCATION) != PackageManager.PERMISSION_GRANTED) {
    // You need to ask the user to enable the permissions
} else {
    LocationTracker tracker = new LocationTracker(getApplicationContext()) {
        @Override
        public void onLocationFound(Location location) {
            LatLng latLng = new LatLng(location.getLatitude(), location.getLongitude());
            ...
        }

        @Override
        public void onTimeout() {

        }
    };
    tracker.startListening();
}
```

Can you help me, please?. Thanks!

**Comment by mauriballes** [comment]
You need to try use 'High Accurancy'. For me It is works!
![Configuration](https://user-images.githubusercontent.com/16750543/32407539-07d1f4b2-c161-11e7-8384-a46a1f17b223.jpg)
